######################################################################
#
# File name : I_DNN_multiple_images_tb_compile.do
# Created on: Wed Mar 08 18:01:46 +0100 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/ieee_proposed
vlib modelsim_lib/msim/xil_defaultlib

vmap ieee_proposed modelsim_lib/msim/ieee_proposed
vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vcom  -2008 -work ieee_proposed  \
"../../../../../../src/DNN/fixed_pkg_2008.vhd" \

vcom  -2008 -work xil_defaultlib  \
"../../../../../../src/DNN/I_DNN_package.vhd" \
"../../../../../../src/DNN/I_DNN_MI_package.vhd" \
"../../../../../../src/NORM/TEST_ARCHITECTURE_PACKAGE.vhd" \
"../../../../../../src/NORM/NVME_FRAMEWORK_PACKAGE.vhd" \
"../../../../../../src/NORM/COMMON_PACKAGE.vhd" \
"../../../../../../src/NORM/INTERMITTENCY_EMULATOR_package.vhd" \
"../../../../../../src/NORM/var_counter.vhd" \
"../../../../../../src/DNN/I_FSM_layer.vhd" \
"../../../../../../src/DNN/I_neuron.vhd" \
"../../../../../../src/DNN/weight_memory.vhd" \
"../../../../../../src/DNN/I_layer.vhd" \
"../../../../../../src/NORM/nv_reg_emu.vhd" \
"../../../../../../src/NORM/trace_ROM.vhd" \
"../../../../../../src/NORM/nv_reg.vhd" \
"../../../../../../src/NORM/intermittency_emulator.vhd" \
"../../../../../../src/NORM/scaler.vhd" \
"../../../../../../src/NORM/counter.vhd" \
"../../../../../../src/DNN/test_sfixed.vhd" \

vcom  -93 -work xil_defaultlib  \
"../../../../../../src/NORM/instant_pwr_calc.vhd" \
"../../../../../../src/NORM/power_approximation.vhd" \
"../../../../../../src/NORM/pwr_consumption_val_ROM.vhd" \
"../../../../../../src/NORM/mult.vhd" \
"../../../../../../src/NORM/rams_sp_rf.vhd" \

vcom  -2008 -work xil_defaultlib  \
"../../../../../../src/DNN/ReLU.vhd" \
"../../../../../../src/DNN/VAR_CNTR_PROCESS.vhd" \
"../../../../../../src/DNN/unary_or.vhd" \
"../../../../../../src/DNN/Sigmoid.vhd" \
"../../../../../../src/DNN/I_DNN.vhd" \
"../../../../../../src/DNN/SOFT_MAX.vhd" \
"../../../../../../src/NORM/fsm_nv_reg_cb.vhd" \

vcom  -93 -work xil_defaultlib  \
"../../../../../../src/NORM/fsm_nv_reg_db.vhd" \

vcom  -2008 -work xil_defaultlib  \
"../../../../../../test/I_DNN_multiple_images_tb.vhd" \
"../../../../../../test/I_layer_tb.vhd" \
"../../../../../../test/I_DNN_tb.vhd" \
"../../../../../../test/I_layer_tb_hazard_scenarios.vhd" \

vcom  -93 -work xil_defaultlib  \
"../../../../../../test/mult_tb.vhd" \

quit -force

